name: pair

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install libimobiledevice
        run: sudo apt-get update && sudo apt-get install -y libimobiledevice-utils
      - name: Generate Pair Record
        run: idevicepair -u ${{ secrets.UDID }} pair
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pair_record
          path: /var/lib/lockdown/${{ secrets.UDID }}.plist
